

name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build . --file Dockerfile --tag hmk/pemkey:latest
          docker push hmk/pemkey:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          env: production
          ref: main
          desc: "Starting deployment to Z.com VPS"

      - name: Set up SSH key for Z.com VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/pemkey.pem
          chmod 600 ~/.ssh/pemkey.pem
          ssh-keygen -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Z.com VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/pemkey.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/calculator/
            git pull origin main
            docker compose down
            docker compose up --build -d
          EOF

      - name: Mark Deployment as Successful
        uses: bobheadxi/deployments@v1
        if: success()
        with:
          step: finish
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          env: production
          status: success
          desc: "Deployment to Z.com VPS successful!"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Mark Deployment as Failed
        uses: bobheadxi/deployments@v1
        if: failure()
        with:
          step: finish
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          env: production
          status: failure
          desc: "Deployment to Z.com VPS failed."
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}














